import Foundation

/// Uses Telegram's selected language, including regional Russian packs, with English as the fallback.
public func dgLocalized(_ text: String, languageCode: String) -> String {
    let language = languageCode.lowercased().replacingOccurrences(of: "_", with: "-")
    if language == "ru" || language.hasPrefix("ru-") { return text }
    if let translated = dgEnglishStrings[text] { return translated }
    if text == text.uppercased(), let pair = dgEnglishStrings.first(where: { $0.key.uppercased() == text }) {
        return pair.value.uppercased()
    }
    // Only numeric labels are formatted here; editable text and usernames never pass through this function.
    for (suffix, replacement) in [(" сек.", " sec."), (" секунд", " seconds")] {
        if text.hasSuffix(suffix), Int(text.dropLast(suffix.count)) != nil {
            return String(text.dropLast(suffix.count)) + replacement
        }
    }
    return text
}

private let dgEnglishStrings: [String: String] = [
    "Настройки Donutgram": "Donutgram Settings",
    "Настройки сообщений": "Message Settings",
    "Время пересылки": "Forwarded Message Date",
    "Копировать название": "Copy Button Text",
    "Копировать Callback-данные": "Copy Callback Data",
    "Меню ссылки": "Link Options",
    "Так будет выглядеть входящее сообщение": "This is how incoming messages will look",
    "И исходящее сообщение": "And an outgoing message",
    "Вау!": "Wow!",
    "Ого, какой милый!": "Wow, so cute!",
    "Основные": "General",
    "Режим призрака": "Ghost Mode",
    "Включен": "Enabled",
    "Выключен": "Disabled",
    "Сохранять удаленки": "Save Deleted Messages",
    "Полупрозрачные удаленки": "Translucent Deleted Messages",
    "Сохранять историю правок": "Save Edit History",
    "Сохранять одноразки": "Save View-Once Media",
    "Сохранять в чатах с ботами": "Save Messages in Bot Chats",
    "Видеть удаленные подарки": "Show Removed Gifts",
    "Сохранять запрещенные истории": "Save Protected Stories",
    "Обход блокировок GIF": "Bypass GIF Restrictions",
    "Пересылка": "Forwarding",
    "Запрещенная рассылка": "Allow Restricted Forwarding",
    "Ускорение загрузки": "Download Acceleration",
    "Ускорение отправки": "Upload Acceleration",
    "Ультра использует больше одновременных соединений. На медленном интернете это может мешать загрузке файлов и просмотру видео.": "Ultra uses more simultaneous connections. On slow networks this may affect downloads and video playback.",
    "Другое": "Other",
    "Визуальный номер": "Visual Phone Number",
    "Визуальный рейтинг": "Visual Rating",
    "Визуальные NFT-юзернеймы": "Visual Collectible Usernames",
    "Визуальный ID": "Visual ID",
    "Локальный TG Premium": "Local Telegram Premium",
    "Premium включён локально для этого аккаунта. Сервер Telegram по-прежнему проверяет подписку для платных возможностей.": "Premium is enabled locally for this account. Telegram still checks your subscription for paid features.",
    "ID профиля": "Profile ID",
    "Любой текст": "Any Text",
    "Меняется только ID в вашем профиле на этом устройстве. Пустое поле возвращает настоящий ID. Нажатие на ID копирует настоящий номер Telegram.": "Only the profile ID displayed on this device changes. Leave it empty to show your real ID. Tapping it copies your real Telegram ID.",
    "Уровень": "Level",
    "Укажите уровень от 1 до 100. Значок и его узор выбираются тем же компонентом, что и в Telegram. Пустое поле возвращает реальный рейтинг. Изменение видно только в Donutgram на этом устройстве.": "Choose a level from 1 to 100. The badge uses Telegram's rating component. Leave the field empty to restore the real rating. This change is visible only in Donutgram on this device.",
    "Имена через запятую": "Comma-Separated Usernames",
    "Имена добавляются только локально. Активность и порядок меняются в редакторе имён. Карточка Telegram покажет дату добавления и условную цену от 9 TON. Реальные ссылки, владельцы и данные Telegram не меняются.": "Usernames are added locally. Change their status and order in the username editor. The card shows the date added and a simulated price starting at 9 TON. Real links, owners and Telegram data stay unchanged.",
    "Подмена номера": "Phone Number Override",
    "Показывать другой номер": "Show a Different Number",
    "Меняется только отображение номера в вашем профиле на этом устройстве. Реальный номер Telegram и данные аккаунта остаются прежними.": "Only the phone number displayed in your profile on this device changes. Your real Telegram number and account data stay unchanged.",
    "Никогда": "Never",
    "В режиме призрака": "In Ghost Mode",
    "Всегда": "Always",
    "Параметры режима призрака": "Ghost Mode Options",
    "Читать при действиях": "Mark as Read on Interaction",
    "Использовать отложку": "Use Scheduled Sending",
    "Отправлять без звука": "Send Silently",
    "Предлагать призрака для сторис": "Suggest Ghost Mode for Stories",
    "Параметры призрака": "Ghost Options",
    "Не отправлять": "Do Not Send",
    "Отметки о прочтении сообщений": "Message Read Receipts",
    "Отметки о просмотре историй": "Story View Receipts",
    "Статус «онлайн»": "Online Status",
    "Статус «печатает»": "Typing Status",
    "Автоматический «офлайн»": "Automatic Offline Status",
    "Параметры действуют только при включённом режиме призрака.": "These options work only while Ghost Mode is on.",
    "Отправители увидят, что сообщения прочитаны.": "Senders will see that the messages have been read.",
    "Оформление": "Appearance",
    "Основное": "General",
    "Скрыть премиум статусы": "Hide Premium Badges",
    "Отключить кастомные фоны": "Disable Custom Backgrounds",
    "Скрыть сторис": "Hide Stories",
    "Приложение": "Application",
    "Вкладки": "Tabs",
    "Скрыть панель вкладок": "Hide Tab Bar",
    "Вкладка Контакты": "Contacts Tab",
    "Вкладка Звонки": "Calls Tab",
    "Широкая Панель": "Wide Tab Bar",
    "Профиль": "Profile",
    "ID Профилей": "Profile IDs",
    "Показывать ID диалога": "Display Chat ID As",
    "Показывать дата-центр (DC)": "Show Data Center (DC)",
    "Показывать дату регистрации": "Show Registration Date",
    "Показывать дату создания чата": "Show Chat Creation Date",
    "Показывать взаимный контакт": "Show Mutual Contact",
    "Относительное время онлайна": "Relative Last Seen Time",
    "Скрыть номер телефона": "Hide Phone Number",
    "Отключить рекламу": "Disable Ads",
    "Подтверждение вызова": "Confirm Calls",
    "Предпросмотр": "Preview",
    "Остров прячется под вырезом камеры — его видно только на скриншотах и записи экрана.": "The island is hidden beneath the camera cutout and appears in screenshots and screen recordings.",
    "Остров как у иконки": "Match Island to App Icon",
    "Выбираешь иконку — остров меняется на такой же.": "Choosing an app icon also changes the island to match.",
    "Иконка и остров выбираются отдельно.": "Choose the app icon and island independently.",
    "Иконка": "App Icon",
    "Иконка и остров": "Icon and Island",
    "Иконка приложения": "App Icon",
    "ID диалога": "Chat ID",
    "Внешний вид": "Chat Appearance",
    "Фронтальная": "Front",
    "Основная": "Rear",
    "Спрашивать": "Ask Every Time",
    "Стикеры": "Stickers",
    "Скрыть время на стикерах": "Hide Sticker Timestamps",
    "Скрыть галочки на стикерах": "Hide Sticker Checkmarks",
    "Форма стикеров": "Sticker Shape",
    "Стикеры и эмодзи": "Stickers and Emoji",
    "Показывать только добавленные стикеры": "Show Only Added Stickers",
    "Беск. недавние стикеры": "Unlimited Recent Stickers",
    "Скрыть реакции": "Hide Reactions",
    "Сообщения": "Messages",
    "Убрать хвост у сообщений": "Remove Message Tails",
    "Показывать секунды": "Show Seconds",
    "Отключить цветные ответы": "Disable Colored Replies",
    "Заменять «изменено» иконкой": "Replace Edited Label with Icon",
    "Показывать индикатор онлайна": "Show Online Indicator",
    "Скрыть приветственный стикер": "Hide Greeting Sticker",
    "Запятая после упоминания": "Comma After Mentions",
    "Аватарки в упоминаниях": "Avatars in Mentions",
    "Итоги до голосования": "Poll Results Before Voting",
    "Счетчик пересылок в каналах": "Channel Forward Counter",
    "Голос в текст": "Voice to Text",
    "Сервис": "Service",
    "Запись": "Recording",
    "Камера в кружках": "Round Video Camera",
    "Запоминать последнюю камеру": "Remember Last Camera",
    "Слайдер зума": "Zoom Slider",
    "Оставлять зум после щипка": "Keep Zoom After Pinching",
    "Пауза музыки при записи": "Pause Music While Recording",
    "Встроенный микрофон": "Built-In Microphone",
    "Видео": "Video",
    "Перемотка двойным нажатием": "Double-Tap Seek",
    "Отключено": "Disabled",
    "Авто пауза": "Auto Pause",
    "Приостанавливать": "Pause For",
    "Скрывать архив из списка чатов": "Hide Archive from Chat List",
    "Открывать архив при вытягивании": "Pull Down to Open Archive",
    "Каналы": "Channels",
    "Широкие посты в каналах": "Wide Channel Posts",
    "Нижняя кнопка": "Bottom Button",
    "Эффекты": "Effects",
    "Свечение": "Glow",
    "Обсудить": "Discuss",
    "Убрать звук": "Mute",
    "Скрыть": "Hide",
    "«Обсудить» открывает группу обсуждения канала. В каналах без обсуждения кнопка скрыта.": "Discuss opens the channel's linked discussion group. The button is hidden in channels without a discussion group.",
    "Свечение аватарок": "Avatar Glow",
    "Свечение реакций": "Reaction Glow",
    "Ответы на стикеры": "Sticker Replies",
    "Ответы": "Replies",
    "Цвета": "Colors",
    "Эмодзи": "Emoji",
    "Фон": "Background",
    "Список чатов": "Chat List",
    "Снег": "Snow",
    "Скрыть статус соединения": "Hide Connection Status",
    "Скрыть эмодзи-статус": "Hide Emoji Status",
    "Заголовок по центру": "Centered Title",
    "Скрыть строку поиска": "Hide Search Bar",
    "Текст в заголовке": "Title Text",
    "Папки внизу": "Folders at the Bottom",
    "Кружки": "Round Videos",
    "Голосовые сообщения": "Voice Messages",
    "Прослушивание голосовые сообщения": "Voice Message Playback",
    "Юзернейм": "Username",
    "Никнейм": "Display Name",
    "Чаты": "Chats",
    "Голосовых": "Voice Messages",
    "Кружков": "Round Videos",
    "Скачивание": "Downloads",
    "Скачивать TikTok": "Download TikTok Videos",
    "Скачивать YT Shorts": "Download YouTube Shorts",
    "Подписывать": "Add Attribution",
    "Авто": "Auto",
    "Telegram, пока он может расшифровать сообщение сам — с Premium или бесплатными попытками. Иначе Apple.": "Use Telegram when transcription is available through Premium or free attempts. Otherwise use Apple.",
    "Telegram использует облачный сервис распознавания.": "Telegram uses cloud speech recognition.",
    "Apple распознаёт речь на устройстве, а если язык не поддерживается — на серверах Apple.": "Apple recognizes speech on your device, or on Apple's servers when the language is not supported on-device.",
    "Группы": "Groups",
    "Личные чаты": "Private Chats",
    "Поддержка": "Support",
    "Раздел подготовлен для ссылок на поддержку и информацию о Donutgram.": "Support links and information about Donutgram will appear here.",
    "Необходим перезапуск": "Restart Required",
    "Перезапустить сейчас": "Restart Now",
    "Скопировать ссылку": "Copy Link",
    "Копировать ссылку": "Copy Link",
    "Поделиться ссылкой": "Share Link",
    "Остров": "Island",
    "Скопировать название": "Copy Name",
    "Ссылка": "Link",
    "Откл.": "Off",
    "Быстро": "Fast",
    "Ультра": "Ultra",
    "Маленький": "Small",
    "Большой": "Large",
    "Размер стикеров": "Sticker Size",
    "Сбросить настройки стикеров": "Reset Sticker Settings",
    "По умолчанию": "Default",
    "Закруглённая": "Rounded",
    "Сообщение": "Message",
    "Основной": "Default",
    "Кольцо": "Ring",
    "Надкушенный": "Bitten",
    "Пончик-чат": "Chat Donut",
    "Сердечко": "Heart",
    "Мордочка": "Kawaii",
    "Свинопончик": "Pig Donut",
    "Пиксель": "Pixel",
    "Планета": "Planet",
    "Самолётик": "Paper Plane",
    "Глазурь": "Glaze",
    "Перспектива": "Perspective",
    "Стикер": "Sticker",
    "Котопончик": "Cat Donut",
    "Хром": "Chrome",
    "Стекло": "Glass",
    "Призрак": "Ghost",
    "Кофе": "Coffee",
    "Акварель": "Watercolor",
    "Бойкиссер": "Boykisser",
    "Бойкиссер 2": "Boykisser 2",
    "Котик": "Cat",
    "Прочитать все на сервере": "Read All on Server",
    "Прочитать все сообщения?": "Read all messages?",
    "Прочитать": "Read",
    "Отмена": "Cancel",
    "Все сообщения прочитаны": "All Messages Read",
    "Не удалось прочитать все сообщения. Попробуйте ещё раз.": "Couldn't read all messages. Please try again.",
    "Отправить как голосовое": "Send as Voice Message",
    "Не удалось преобразовать музыку в голосовое сообщение.": "Couldn't convert this audio to a voice message.",
    "Воспроизвести": "Play",
    "Теневой бан": "Shadow Ban",
    "Убрать из теневого бана": "Remove from Shadow Ban",
    "%@ в теневом бане": "%@ is shadow banned",
    "%@ убран из теневого бана": "%@ is no longer shadow banned",
    "Показать скрытые сообщения": "Show Shadow-Banned Messages",
    "Спрятать скрытые сообщения": "Hide Shadow-Banned Messages",
    "Добавить": "Add",
    "Убрать": "Remove",
    "Неизвестный": "Unknown",
    "бот": "bot",
    "пользователь": "user",
    "канал": "channel",
    "Сообщения этих людей скрыты в группах, комментариях и каналах только на этом устройстве. Они об этом не узнают. Личные чаты не меняются.": "Messages from these people are hidden in groups, comments and channels on this device only. They won't be notified. Private chats are not affected.",
    "Скрытое сообщение": "Hidden Message",
    "Автор в теневом бане": "The author is shadow banned",
    "Сообщение скрыто теневым баном": "This message is hidden by shadow ban"
]
